services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/sky/docker-compose/plex/library:/config
      - /media/sky/datapartition3/plex/tv_shows:/tv
      - /media/sky/datapartition22/plex/tv_shows:/tv2
      - /media/sky/datapartition3/plex/movies:/movies
      - /media/sky/datapartition22/plex/movies:/movies2
    restart: unless-stopped
    
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - TRANSMISSION_WEB_HOME= #optional
      - USER=sky
      - PASS= <PASSWORD>
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /home/sky/docker-compose/transmission/config:/config
      - /media/sky/datapartition3/transmission/downloads:/downloads
      - /home/sky/docker-compose/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/sky/docker-compose/jackett/config:/config
      - /media/sky/datapartition3/transmission/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/sonarr/config:/config
      - /media/sky/datapartition3/plex/tv_shows:/tv
      - /media/sky/datapartition22/plex/tv_shows:/tv2
      - /media/sky/datapartition3/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/radarr/config:/config
      - /media/sky/datapartition3/plex/movies:/movies
      - /media/sky/datapartition22/plex/movies:/movies2
      - /media/sky/datapartition3/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LANG=en
      - WG_HOST=<PUBLIC IP>
      - PASSWORD=<PASSWORD>
      - PORT=51821 
      - WG_PORT=51820 # Have to forward this port
    volumes:
      - /home/sky/docker-compose/wg-easy/:/etc/wireguard
    ports:
      51820:51820/udp
      51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
