services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 6gb
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/sky/docker-compose/plex/library:/config
      - /mnt/a/plex/tv_shows:/tv
      - /mnt/b/plex/tv_shows:/tv2
      - /mnt/a/plex/movies:/movies
      - /mnt/b/plex/movies:/movies2
    restart: unless-stopped
    
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - TRANSMISSION_WEB_HOME= #optional
      - USER=sky
      - PASS={PASSWORD}
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /home/sky/docker-compose/transmission/config:/config
      - /mnt/a/transmission/downloads:/downloads
      - /home/sky/docker-compose/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/sky/docker-compose/jackett/config:/config
      - /mnt/a/transmission/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/sonarr/config:/config
      - /mnt/a/plex/tv_shows:/tv
      - /mnt/b/plex/tv_shows:/tv2
      - /mnt/a/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/radarr/config:/config
      - /mnt/a/plex/movies:/movies
      - /mnt/b/plex/movies:/movies2
      - /mnt/a/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
      
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/bazarr/config:/config
      - /mnt/a/plex/tv_shows:/tv
      - /mnt/b/plex/tv_shows:/tv2
      - /mnt/a/plex/movies:/movies
      - /mnt/b/plex/movies:/movies2
    ports:
      - 6767:6767
    restart: unless-stopped
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /home/sky/docker-compose/audiobookshelf/audiobooks:/audiobooks
      - /home/sky/docker-compose/audiobookshelf/config:/config
      - /home/sky/docker-compose/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Edmonton
      
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Edmonton
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /home/sky/docker-compose/overseerr/config:/app/config
    restart: unless-stopped

  flaresolverr:
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    container_name: flaresolverr
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Edmonton
    ports:
      - "${PORT-8191}:8191"
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
      - '--web.listen-address=0.0.0.0:9100'
    ports:
      - '9100:9100'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
