services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /home/timothy/docker-compose/npm/data:/data
      - /home/timothy/docker-compose/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/config/prometheus.yml"
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LANG=en
      - WG_HOST=wgeasy.winston-server.com
      - PASSWORD_HASH=$$2a$$12$$vGQPEAFP/cQc7bFPEBJJHubvI1sU6xi3s7hT4eAJFubiD79ZWYxmm
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - /home/sky/docker-compose/wg-easy/:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - /home/sky/docker-compose/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      - pihole_network
    environment:
      - TZ=Your/Timezone
      - WEBPASSWORD=  # Replace with password
      - ServerIP=192.168.0.80
    ports:
      - "7080:80"  # Map external port 7080 to internal port 80 (HTTP)
      - "7443:443" # Map external port 7443 to internal port 443 (HTTPS)
      - "53:53"    # DNS port (still using 53 for DNS)
      - "53:53/udp" # DNS over UDP
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped


volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  pihole_network:
    driver: bridge

