services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /home/timothy/docker-compose/npm/data:/data
      - /home/timothy/docker-compose/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
