global:
  scrape_interval: 15s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090

# Example job for node_exporter
 - job_name: 'node_exporter'
   static_configs:
     - targets: ['node_exporter:9100']

# Example job for cadvisor
 - job_name: 'cadvisor'
   static_configs:
     - targets: ['cadvisor:8080']

 - job_name: 'node_exporter_winston'
   static_configs:
     - targets: ['192.168.1.92:9100']

 - job_name: 'cadvisor_winston'
   static_configs:
     - targets: ['192.168.1.92:8080']
